import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'STHL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#262626] w-full min-h-screen flex items-center justify-center'>{children}</body>
    </html>
  )
}

